version: build-{build}
configuration: Release
platform: Win32
environment:
  TOOLCHAIN_VER: 10.0
before_build:
  - cmd: >-
      set PATH=C:\Program Files (x86)\MSBuild\%TOOLCHAIN_VER%\Bin;%PATH%
      call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VER%\VC\vcvarsall.bat"
build:
  project: CoolQHttpApi.sln