branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2017

platform:
  - x86

configuration:
  - Release

environment:
  VCPKG_ROOT: C:\tools\vcpkg

cache: c:\tools\vcpkg\installed\ -> vcpkg-commit.txt, cmake/x86-windows-static-custom.cmake

install:
  - git submodule init
  - git submodule update
  - powershell .\scripts\prepare.ps1

build_script:
  - powershell .\scripts\generate.ps1 %CONFIGURATION%
  - powershell .\scripts\build.ps1 %CONFIGURATION%

artifacts:
  - path: build/Release/Release/*.dll
  - path: build/Release/Release/*.json
